import { Router, type IRouter } from "express";
import healthRouter from "./health";
import chatRouter from "./chat";
import psyChatRouter from "./psy-chat";
import telegramRouter from "./telegram";
import signalsRouter from "./signals";
import channelsRouter from "./channels";
import marketRouter from "./market";
import operatorsRouter from "./operators";
import botStatusRouter from "./bot-status";
import testInterpretRouter from "./test-interpret";
import psyAutopsyRouter from "./psy-autopsy";
import psyWeeklyReportRouter from "./psy-weekly-report";
import adminConfigRouter from "./admin-config";
import marketProxyRouter from "./market-proxy";
import oracleProxyRouter from "./oracle-proxy";
import vaultRouter from "./vault";
import certificatesRouter from "./certificates";
import newsRouter from "./news";
import oneInchRouter from "./oneinch";
import membersRouter from "./members";
import botXRouter from "./bot-x";
import exchangeRouter from "./exchange";
import intelligenceRouter from "./intelligence";
import freeAuthRouter from "./free-auth";
import supportChatRouter from "./support-chat";
import apiKeysRouter from "./api-keys";
import psyOracleRouter from "./psy-oracle";
import marketDataRouter from "./market-data";
import whaleIntelRouter from "./whale-intel";
import coinglassRouter from "./coinglass";
import telegramListenerRouter from "./telegram-listener";
import psyBrainRouter from "./psy-brain";
import oracleFeedsRouter from "./oracle-feeds";
import psyAlgoRouter from "./psy-algo";
import scanRouter from "./scan";
import buffettRouter from "./buffett";
import psyLaunchRouter from "./psy-launch";
import altcoinSignalsRouter from "./altcoin-signals";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/chat", chatRouter);
router.use(psyChatRouter);
router.use(telegramRouter);
router.use(signalsRouter);
router.use(channelsRouter);
router.use(marketRouter);
router.use(operatorsRouter);
router.use(botStatusRouter);
router.use(testInterpretRouter);
router.use(psyAutopsyRouter);
router.use(psyWeeklyReportRouter);
router.use(adminConfigRouter);
router.use(oracleProxyRouter);
router.use(marketProxyRouter);
router.use(vaultRouter);
router.use(certificatesRouter);
router.use(newsRouter);
router.use(oneInchRouter);
router.use(membersRouter);
router.use(botXRouter);
router.use(exchangeRouter);
router.use(intelligenceRouter);
router.use(freeAuthRouter);
router.use(supportChatRouter);
router.use(apiKeysRouter);
router.use(psyOracleRouter);
router.use(marketDataRouter);
router.use(whaleIntelRouter);
router.use(coinglassRouter);
router.use(telegramListenerRouter);
router.use(psyBrainRouter);
router.use(oracleFeedsRouter);
router.use(psyAlgoRouter);
router.use(scanRouter);
router.use(buffettRouter);
router.use(psyLaunchRouter);
router.use(altcoinSignalsRouter);

export default router;
