import { Router, type IRouter } from "express";
import healthRouter from "./health";
import chatRouter from "./chat";
import psyChatRouter from "./psy-chat";
import telegramRouter from "./telegram";
import copyTradeNotifyRouter from "./copy-trade-notify";
import signalsRouter from "./signals";
import channelsRouter from "./channels";
import marketRouter from "./market";
// (julio 21 2026) Jorge pidió de vuelta la gestión de operadores — estaba
// completa (tabla psy_operators, rutas /admin/operators, y el frontend en
// signals-realtime.tsx ya la esperaba con el mismo header X-PSY-Token) pero
// el router había quedado desconectado acá. Se reactiva.
import operatorsRouter from "./operators";
import botStatusRouter from "./bot-status";
import testInterpretRouter from "./test-interpret";
import psyAutopsyRouter from "./psy-autopsy";
import psyWeeklyReportRouter from "./psy-weekly-report";
import adminConfigRouter from "./admin-config";
import marketProxyRouter from "./market-proxy";
import degateProxyRouter from "./degate-proxy";
import oracleProxyRouter from "./oracle-proxy";
import vaultRouter from "./vault";
import certificatesRouter from "./certificates";
import newsRouter from "./news";
import oneInchRouter from "./oneinch";
import membersRouter from "./members";
import telegramChannelsRouter from "./telegram-channels";
import botXRouter from "./bot-x";
import exchangeRouter from "./exchange";
import intelligenceRouter from "./intelligence";
import freeAuthRouter from "./free-auth";
import supportChatRouter from "./support-chat";
import apiKeysRouter from "./api-keys";
import psyOracleRouter from "./psy-oracle";
import marketDataRouter from "./market-data";
import whaleIntelRouter from "./whale-intel";
import coinglassRouter from "./coinglass";
import telegramListenerRouter from "./telegram-listener";
import psyBrainRouter from "./psy-brain";
import psyBrainLiveRouter from "./psy-brain-live";
import oracleFeedsRouter from "./oracle-feeds";
import psyAlgoRouter from "./psy-algo";
import scanRouter from "./scan";
import buffettRouter from "./buffett";
import pumpLiveRouter from "./pump-live";
import marketPulseRouter from "./market-pulse";
import oiRadarRouter from "./oi-radar";
import psyLaunchRouter from "./psy-launch";
import psyWhalesRouter from "./psy-whales";
import altcoinSignalsRouter from "./altcoin-signals";
import whitelistRouter from "./whitelist";
import iaTradingProxyRouter from "./ia-trading-proxy";
import iaTradingBolsaRouter from "./ia-trading-bolsa";
import cryptoIndicesRouter from "./crypto-indices";
import iaSignalsRouter from "./ia-signals";
import superadminAuthRouter from "./superadmin-auth"; // montar ANTES de freeAuthRouter: mismo path /auth/superadmin-login, esta versión trae TOTP
import globalLiquidityRouter from "./global-liquidity"; // PSY LIQUIDITY FUEL — página nueva (Educación/Pro/Elite)

const router: IRouter = Router();

router.use(healthRouter);
router.use("/chat", chatRouter);
router.use(psyChatRouter);
router.use(telegramRouter);
router.use(copyTradeNotifyRouter);
router.use(signalsRouter);
router.use(channelsRouter);
router.use(marketRouter);
router.use(operatorsRouter);
router.use(botStatusRouter);
router.use(testInterpretRouter);
router.use(psyAutopsyRouter);
router.use(psyWeeklyReportRouter);
router.use(adminConfigRouter);
router.use(oracleProxyRouter);
router.use(marketProxyRouter);
router.use(degateProxyRouter);
router.use(vaultRouter);
router.use(certificatesRouter);
router.use(newsRouter);
router.use(oneInchRouter);
router.use(membersRouter);
router.use(telegramChannelsRouter);
router.use(botXRouter);
router.use(exchangeRouter);
router.use(intelligenceRouter);
router.use(superadminAuthRouter);
router.use(freeAuthRouter);
router.use(supportChatRouter);
router.use(apiKeysRouter);
router.use(psyOracleRouter);
router.use(marketDataRouter);
router.use(whaleIntelRouter);
router.use(coinglassRouter);
router.use(telegramListenerRouter);
router.use(psyBrainRouter);
router.use(psyBrainLiveRouter);
router.use(oracleFeedsRouter);
router.use(psyAlgoRouter);
router.use(scanRouter);
router.use(buffettRouter);
router.use(pumpLiveRouter);
router.use(marketPulseRouter);
router.use(oiRadarRouter);
router.use(psyLaunchRouter);
router.use(psyWhalesRouter);
router.use(altcoinSignalsRouter);
router.use(whitelistRouter);
router.use(iaTradingProxyRouter);
router.use(iaTradingBolsaRouter);
router.use(cryptoIndicesRouter);
router.use(iaSignalsRouter);
router.use(globalLiquidityRouter);

export default router;
